### ISSUE TITLE
MythicMobs do not work in 1.21.

### ISSUE THREAD

**Issue by Netscape7** [IzzelAliz/Arclight#1494]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.21.1-1.0.0-SNAPSHOT-2f61580

### OS & Java versions

java version 21.0.3 by Eclipse Adoptium; OS Windows 11 arch amd64 version 10.0

### Plugins and Mods

```raw
Plugins (1): MythicMobs
```

### Description

MythicMobs doesn't work and gives me the error java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.ItemMeta.displayName(net.kyori.adventure.text.Component)'.
It worked fine with Paper and Spigot, so this is a problem caused by Arclight.

### Step to reproduce

1. Download the latest version of Arclight FeudalKings.
2. Download MythicMobs 5.7.1.
3. Start the server.

### Logs

[latest.log](https://github.com/user-attachments/files/17056324/latest.log)

**Comment by qyl27** [comment]
I found it could be reproduced in the latest Spigot build. It should be considered as a problem of MythicMobs.  
It used something from Paper API that we haven't fully supported.

**Comment by qyl27** [comment]
About Paper API supporting, please refer #47
