### ISSUE TITLE
Plugin send message error

### ISSUE THREAD

**Issue by Water-Innit** [IzzelAliz/Arclight#1329]
### I have confirmed that ...

- [X] Arclight is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Forge

### Arclight version

arclight-1.20.1-1.0.5-1a8925b

### OS & Java versions

Windows 11 x64 java version "21.0.2" 2024-01-16 LTS

### Plugins and Mods

```raw
Broadcast v2.3 plugin
```

### Description

Helllo i am a plugin developer and people who are using my plugin are getting errors,

From what i can see it it is due to not being able to access net.md_5.bungee.api.chat.BaseComponent
This works fine on spigot 1.20.1 but not on this.

Is this function renamed or relocated in arclite so i am able to reconfigure this so i can release a fix to some of the users. 

The main error line is:
java.lang.NoSuchMethodError: 'void org.bukkit.entity.Player.sendMessage(net.md_5.bungee.api.chat.BaseComponent)'
Unless it is a renamed function for Player.sendMessage

Please let me know if you need to know anymore information

Kind regards

Water

### Step to reproduce

1. Install plugin https://www.spigotmc.org/resources/broadcast-fully-manageable-broadcast-plugin.80772/?__cf_chl_tk=JKMrJQIGE8prGuYZ23hiq8JU.D9Alj.2OXD6GEWVuLA-1713894406-0.0.1.1-1621
2. run server
3. Join server as player

### Logs

[latest.log](https://github.com/IzzelAliz/Arclight/files/15081666/latest.log)
